import Head from 'next/head';
import Header from '../components/Header';

export default function Home() {
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex justify-between items-center bg-yellow-400 border-y border-black py-10 lg:py-0">
        <div className="px-10 space-y-5">
          <h1 className="text-6xl mx-w-xl font-serif ">
            <span className="underline decoration-black decoration-4">
              WebSite
            </span>{' '}
            occaecat consequat labore laboris deserunt.
          </h1>
          <h2>
            Culpa ea ad minim voluptate adipisicing aute eu ea magna nulla.
          </h2>
        </div>
        <div>
          <img
            className="hidden md:inline-flex h-32 lg:h-full"
            src="https://img.icons8.com/ios-filled/250/000000/medium-monogram--v1.png"
            alt=""
          />
        </div>
      </div>
      {/* Posts */}
    </div>
  );
}
